config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  resources :articles do
    collection do
      get :welcome
      post :set_hot
      post :sort
    end
  end

  devise_for :users

  resources :users do
    collection do
      get :welcome
      get :application
    end
  end


  root to: "articles#welcome"
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :category

  def self.categories
    [["生活", 1],["技术", 2]]
  end

  def self.title category_id
    if category_id == '1'
      '生活博客'
    elsif category_id == '2'
      '技术博客'
    elsif category_id == '3'
      '音乐模因'
    elsif category_id == '4'
      '翻译文章'
    end
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :articles
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :get_by_id, :only => [:show, :edit, :update, :destroy, :set_hot]

  def index
    @articles = Article.where("category_id = ?", params[:category_id]).order("date desc").page(params[:page]).per(30)
   #@articles = Article.where("category_id = ?", params[:category_id]).order("position").page(params[:page]).per(30) if Article.last(25).first.position.present?
    @articles = @articles.where("title like '%#{params[:title_or_content]}%' or
                content like '%#{params[:title_or_content]}%'") if params[:title_or_content].present?
  end

  def show
    @article.visited_count += 1
    @article.save
  end

  def edit
  end

  def update
    @article.update params[:article]
    if @article.category_id == 1
      redirect_to articles_path(category_id: 1)
    else
      redirect_to articles_path(category_id: 2)
    end
    flash[:success] = "修改成功"
  end

  def new
    @article = Article.new
  end

  def create
    article = Article.create params[:article]
    if article.category_id == 1
      redirect_to articles_path(category_id: 1)
    else
      redirect_to articles_path(category_id: 2)
    end
    flash[:success] = "新建成功"
  end

  def destroy
    @article.delete
    flash[:success] = "删除成功"
    redirect_to :back
  end

  def welcome
  end

  def set_hot
    @article.is_hot = true
    @article.date = Time.now.strftime("%Y-%m-%d")
    @article.save
    flash[:success] = "置顶成功"
    redirect_to articles_path(category_id: 2)
  end

  def sort
    if params[:articles].present?
      JSON.parse(params[:articles]).each_with_index do |article, index|
        article_id= article["id"]
        position = index + 1
        article = Article.find(article_id)
        article.update_attribute("position", position)
      end
    end
    render nothing: true
  end

  private
  def get_by_id
    @article = Article.find params[:id]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :get_by_id, :only => [:show, :edit, :update ]

  def index
    @user = User.all
  end

  def show
  end

  def edit
  end

  def update
    @user.update params[:user]
    redirect_to users_path
  end

  private
  def get_by_id
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # 分页
  def pagination(records)
    render '/layouts/pagination', records: records
  end
end

app/views/articles/_form.html.erb
<style>
.cke_contents{
  height: 700px !important;
}
</style>
<%= form_for @article do |f| %>
  <%= f.label :title, "标题:" %> <br/>
  <%= f.text_field :title, size: 40, placeholder: "请输入标题" %>
  <br/>
  <br/>
  <%= f.label :content, "内容:" %> <br/>
  <p style="width: 80%; margin: 0 auto;"> <%= f.cktext_area :content, placeholder: "请输入正文内容" %> </p>
  <br/>
  <%= f.label :category_id, "分类" %>
  <%= f.select :category_id, options_for_select([["生活", 1],["技术", 2],["音乐", 3],["翻译", 4]],2) %>
  <br/>
  <%= f.label :date, "日期:" %>
  <%= f.text_field :date, :class=>"datepicker_input" %>
  <br/>
  <br/>
  <%= f.submit "提交", :class => "btn btn-primary" %>
<% end %>

<script>
$("form").validate({
  rules:{
    "article[title]":"required",
    "article[content]":{
    "required":true,
    },
  },
  messages:{
    "article[title]":"请输入标题",
    "article[content]":{
    "required":"请输入正文内容",
    },
  }
});
</script>

app/views/articles/edit.html.erb
<div style="width: 80%;
  height: 1200px;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.73);
  text-align: center;
  padding-top: 35px;
  margin-top: -30px;
  font-size: 18px;
	overflow: auto;">

  <!--
  <label for="datetimepicker">时间：</label><br/>
	<input type="text" id="datetimepicker"/><br/>
  -->

  <%= render :partial => "form" %><br/>

  <% if @article.category_id ==1 %>
    <%= link_to "返回博客列表", articles_path(category_id: 1) %>
  <% else %>
    <%= link_to "返回博客列表", articles_path(category_id: 2) %>
  <% end %>
</div>

  <!--
  <script>
    $('#datetimepicker').datetimepicker({
      format: 'yyyy-mm-dd hh:ii'
    });
  </script>
  -->

app/views/articles/index.html.erb
<div style="width: 80%;
  min-height: 800px;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.73);
  text-align: center;
  padding-top: 35px;
  margin-top: -30px;
  overflow: auto;">

  <h2 style="margin-bottom: 20px; color: #20537f; margin-top: 0;"> <%= Article.title params[:category_id] %> </h2>

  <%= form_tag articles_path, :method => 'get'  do %>
    <%= hidden_field_tag :category_id, params[:category_id] %>
    <%= text_field_tag :title_or_content, params[:title_or_content], placeholder: "模糊匹配,全文,如:ruby on rails", style: "width: 250px; background-color: rgba(241, 241, 241, 0.74);" %>
    <%= submit_tag "搜索" %>
  <% end %>
  <br/>
  <br/>

  <div style="font-size: 18px;">
    <table style="width: 100%; text-align: center;" class="table table-bordered table-hover">
      <thead>
        <tr>
          <th style="width: 20%; text-align: center;">时间</td>
          <th style="text-align: center;">标题</td>
        <% if current_user.present? %>
          <th colspan=4 style="width: 12%; text-align: center;">操作</td>
        <% end %>
        </tr>
      </thead>

      <tbody id="article_table" >
        <% @articles.each do |article| %>
          <tr data-id = '<%= article.id %>' class="ui-state-default">
            <td style="vertical-align: middle;"><%= article.date %></td>
            <td style="text-align: left; margin-left: 10px;">
              <%= link_to article.title, article %>
              <%= "("+ "#{article.visited_count}"+")" %>
            </td>
            <% if current_user.present? %>
              <td style="vertical-align: middle;"><%= link_to "编辑", edit_article_path(article), class: "btn btn-primary btn-xs" %></td>
              <td style="vertical-align: middle;"><%= link_to "删除", article, :method => :delete, data: { confirm: "确定删除该文章么?" },  class: "btn btn-danger btn-xs"  %></td>
              <td style="vertical-align: middle;"><%= link_to "置顶", set_hot_articles_path(id: article.id), :id => "zhi_ding", data: { confirm: "确定要置顶该文章么,会改变创建时间?" }, :method => :post, class: "btn btn-success btn-xs" %></td>
              <!--<td><a href="javascript:showSuccessToast();">not sticky</a> </td> -->
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <div class="table-actions-bottom">
      <%= pagination @articles %><br/>
    </div>

    <% if current_user.present? %>
      <%= link_to "创建博客", new_article_path, class: "btn btn-primary", style: "margin-bottom: 30px;"%>
    <% end %>
  </div>
</div>

<script>
    $('#article_table').sortable({
      opacity: 0.6,
      revert: true,
      cursor: 'move',
      update: function() {
        neworder = new Array();
        $(this).children().each(function() {
          id = $(this).attr("data-id");
          neworder.push({
            id: id
          });
        });

        $.ajax({
          url: "/articles/sort",
          type: "POST",
          data: {
            articles: JSON.stringify(neworder)
          }
        });

        console.log(neworder);
      }
    }).disableSelection();


    $("#zhi_ding").click(function showSuccessToast() {
        $().toastmessage('showSuccessToast', "置顶成功");
    });

    function showStickySuccessToast() {
        $().toastmessage('showToast', {
            text     : 'Success Dialog which is sticky',
            sticky   : true,
            position : 'top-right',
            type     : 'success',
            closeText: '',
            close    : function () {
                console.log("toast is closed ...");
            }
        });
    };

    function showNoticeToast() {
        $().toastmessage('showNoticeToast', "Notice  Dialog which is fading away ...");
    };

    function showStickyNoticeToast() {
        $().toastmessage('showToast', {
             text     : 'Notice Dialog which is sticky',
             sticky   : true,
             position : 'top-right',
             type     : 'notice',
             closeText: '',
             close    : function () {console.log("toast is closed ...");}
        });
    };

    function showWarningToast() {
        $().toastmessage('showWarningToast', "Warning Dialog which is fading away ...");
    };

    function showStickyWarningToast() {
        $().toastmessage('showToast', {
            text     : 'Warning Dialog which is sticky',
            sticky   : true,
            position : 'top-right',
            type     : 'warning',
            closeText: '',
            close    : function () {
                console.log("toast is closed ...");
            }
        });
    };

    function showErrorToast() {
        $().toastmessage('showErrorToast', "Error Dialog which is fading away ...");
    };

    function showStickyErrorToast() {
        $().toastmessage('showToast', {
            text     : 'Error Dialog which is sticky',
            sticky   : true,
            position : 'top-right',
            type     : 'error',
            closeText: '',
            close    : function () {
                console.log("toast is closed ...");
            }
        });
    };

</script>

app/views/articles/new.html.erb
<div style="width: 80%;
  height: 1200px;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.73);
  text-align: center;
  padding-top: 35px;
  margin-top: -30px;
  font-size: 18px;
  overflow: auto;">

  <%= render :partial => "form" %><br/>

  <%= link_to "返回博客列表", articles_path(category_id: 2) %>
</div>

app/views/articles/show.html.erb
<div style="width: 80%;
     margin: 0 auto;
     background-color: rgba(255, 255, 255, 0.73);
     text-align: center;
     padding-top: 35px;
     margin-top: -30px;
     font-size: 18px;
     overflow: auto;">

  <p style="margin-bottom: 20px;
    color: #20537f;
    margin-top: -10px;
    font-size: 30px;
    padding-left: 20%;
    padding-right: 20%;
    font-weight: bold;"><%= @article.title %></p>

  <div style="width: 86%;
    margin: 0 auto;
    min-height: 760px;
    background-color: rgba(255, 255, 255, 0.36);
    margin-bottom: 20px;
    padding: 15px;
    overflow: auto;
    white-space: normal;
    text-align: initial; ">
    <p><%= raw @article.content %></p>
  </div>

  <% if @article.category_id ==1 %>
    <%= link_to "返回列表", articles_path(category_id: 1), class: "btn btn-primary", style: "margin-top: 20px; margin-bottom: 30px;" %>
  <% elsif %>
    <%= link_to "返回列表", articles_path(category_id: 2), class: "btn btn-primary", style: "margin-top: 20px; margin-bottom: 30px;" %>
  <% elsif %>
    <%= link_to "返回列表", articles_path(category_id: 3), class: "btn btn-primary", style: "margin-top: 20px; margin-bottom: 30px;" %>
  <% elsif %>
    <%= link_to "返回列表", articles_path(category_id: 4), class: "btn btn-primary", style: "margin-top: 20px; margin-bottom: 30px;" %>
  <% end %>
</div>

app/views/articles/welcome.html.erb
  <div class="container">
    <div class="row">
      <div class="box" style="margin-bottom: 30px;">
        <div class="col-lg-12 text-center">
          <div id="carousel-example-generic" class="carousel slide">
            <!-- Indicators -->
            <ol class="carousel-indicators hidden-xs">
              <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-example-generic" data-slide-to="1"></li>
              <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            </ol>
            <!-- Wrapper for slides -->
            <div class="carousel-inner">
              <div class="item active">
                <img class="img-responsive img-full" src='<%= asset_path 'slide-1.jpg' %>' alt="">
              </div>
              <div class="item">
                <img class="img-responsive img-full" src='<%= asset_path 'slide-2.jpg' %>' alt="">
              </div>
              <div class="item">
                <img class="img-responsive img-full" src='<%= asset_path 'slide-3.jpg' %>' alt="">
              </div>
            </div>
            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
              <span class="icon-prev"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
              <span class="icon-next"></span>
            </a>
          </div>

          <h2 class="brand-before">
            <small>Welcome to</small>
          </h2>
          <h1 class="brand-name">Cool Blog</h1>
          <hr class="tagline-divider">
          <h2>
            <small>By
              <strong>yuancheng</strong>
            </small>
          </h2>
        </div>
      </div>
    </div>
  </div>

  <script>
    $('.carousel').carousel({
      interval: 3000 //changes the speed
    })
  </script>

app/views/layouts/_messages.html.erb
<%= javascript_tag do %>
  <%- flash.each do |level, message| %>
    Lobibox.alert('<%= level %>', {
        msg: "<%= j(message) %>"
    });
  <%- end %>
<% end %>

app/views/layouts/_pagination.html.erb
<%= paginate records, left: 1, right: 3, theme: 'bootstrap' if records.any? %>
<div class="summary">共有 <strong class="text-info"><%= records.total_count rescue 0 %></strong> 个查询结果</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>文圆承的博客</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <style>
  pre {
    background-color: rgba(245, 245, 245, 0.6);
    font-size: 18px;
  }
  </style>
</head>

<body>
  <%= render 'shared/nav' %>
  <%= yield %>
  <%= render '/layouts/messages' %>
  <%= render 'shared/footer' %>
</body>
</html>

app/views/shared/_footer.html.erb
<!-- /.container -->

<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <% sum = 0
           Article.all.each do |article|
             sum += article.visited_count
           end %>
        <p style="padding: 32px 0;">
          Copyright@文圆承的博客 2016 <br/>
          总访问量:<%= sum %>
        </p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_nav.html.erb
<html>
<head>
  <style>
.register_and_log_on {
}

ul.nav a {
  padding: 25px;
  font-size: 25px;
}
  </style>
</head>

<body>
  <div class="brand">欢迎来到cool的博客</div>
  <div class="address-bar">一个爱音乐的程序员</div>
  <nav class="navbar navbar-default" role="navigation" style="margin-bottom: 30px;">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to '首页', root_path %>
                </li>
                <li>
                    <%= link_to '生活', articles_path(category_id: 1) %>
                </li>
                <li>
                    <%= link_to '技术', articles_path(category_id: 2) %>
                </li>
                <li>
                    <%= link_to '音乐', articles_path(category_id: 3) %>
                </li>
                <li>
                    <%= link_to '翻译', articles_path(category_id: 4) %>
                </li>
                <li>
                    <%= link_to '博主简介', current_user.blank? ? user_path(id: 1) : current_user  %>
                </li>
                <li class="register_and_log_on">
                    <%#= link_to "注册", new_user_registration_path %>
                </li>
                <li class="register_and_log_on">
                  <% if current_user.blank?%>
                    <%= link_to "登录", new_user_session_path %>
                    <% else %>
                    <%= link_to '退出', destroy_user_session_path, method: :delete %>
                  <% end %>
                </li>
            </ul>
        </div>
    </div>
</nav>
</body>
</html>

app/views/users/edit.html.erb
<style>
.cke_contents{
  height: 600px !important;
}
</style>

<div style="width: 80%;
  height: 800px;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.73);
  text-align: center;
  margin-top: -30px;
  font-size: 18px;
  overflow: auto;">

  <%= form_for @user do |f| %>
    <br/>
    <h2 style="margin-bottom: 20px; color: #20537f;">博主简介</h2>
    <p style="width: 80%; margin: 0 auto;"> <%= f.cktext_area :author_intro %> </p>
    <br/>
    <%= f.submit "提交" %>
  <% end %>
    <br/>
  <%= link_to "返回列表页", users_path %>
</div>

app/views/users/index.html.erb
<div style="width: 80%;
  height: 800px;
  margin: 0 auto;
  background-color: rgba(255, 255, 255, 0.73);
  text-align: center;
  padding-top: 35px;
  margin-top: -30px;
  font-size: 18px;">
  <h2 style="margin-bottom: -20px; color: #20537f;">博主简介</h2>

  <div style="width: 80%;
    margin: 0 auto;
    height: 600px;
    margin-bottom: 20px;
    padding: 15px;
    overflow: auto;
    white-space: pre-line;">

    <table style="width: 100%;text-align: center;" class="table table-bordered table-hover">
      <tr>
        <td>时间</td>
        <td>标题</td>
      <% if current_user.present? %>
        <td>操作</td>
      <% end %>
      </tr>

      <% @user.each do |user| %>
      </tr>
        <td><%= user.created_at.strftime('%Y-%m-%d %H:%M:%S') %></td>
        <td><%= link_to user.id, user %></td>
        <% if current_user.present? %>
          <td><%= link_to "编辑", edit_user_path(user)%></td>
        <% end %>
      </tr>
      <% end %>
    </table>
  </div>

  <%= link_to "返回首页", welcome_articles_path %>
</div>

app/views/users/show.html.erb
<div style="width: 80%;
     height: 1000px;
     margin: 0 auto;
     background-color: rgba(255, 255, 255, 0.73);
     text-align: center;
     padding-top: 35px;
     margin-top: -30px;
     font-size: 18px;">

  <h2 style="margin-bottom: 30px; color: #20537f; margin-top: 0;">博主简介</h2>

  <div style="width: 80%;
    margin: 0 auto;
    height: 800px;
    background-color: rgba(255, 255, 255, 0.36);
    margin-bottom: 20px;
    padding: 15px;
    overflow: auto;
    white-space: normal;
    text-indent: 1cm;
    text-align: initial;">
    <p><%= raw @user.author_intro %></p>
  </div>
  <br/>
  <% if current_user.present? %>
    <%= link_to "返回列表页", users_path %>
  <% end %>
</div>